spring:
  application:
    name: authentication
  docker:
    compose:
      enabled: true
      file: ../compose.yaml
  data:
    mongodb:
      database: aws-mongodb
server:
  port: 8090


app:
  authentication:
    secret: wCTLDLCtGQubfHuka4458ER6P9Jqudfh9jwTXkI5CLWGkLxnew
    ttl: 3600