spring:
  application:
    name: product-management
  docker:
    compose:
      enabled: true
      lifecycle-management: start-and-stop
      file: ../compose-with-auth.yaml
      stop:
        command: stop
  data:
    mongodb:
      database: aws-mongodb
      auto-index-creation: true
server:
  port: 8089

app:
  authentication:
    secret: wCTLDLCtGQubfHuka4458ER6P9Jqudfh9jwTXkI5CLWGkLxnew
    ttl: 3600